awslabs/amazon-qldb-driver-go

qldbdriver/qldbdriver.go
qldbdriver/qldbdriver_test.go
qldbdriver/session.go
qldbdriver/session_test.go

Removed the unused retryLimit in session.go.

---

go.mod

Fixed the module name.

---

README.md

Remove redundant information and bad link

---

README.md

#13 
-Update the README to require users to have their projects set up to use Go modules. This will ensure the correct dependencies are installed.

Update readme to require customer to use go modules

---

qldbdriver/communicator.go
qldbdriver/integration_base_test.go
qldbdriver/logger.go
qldbdriver/qldbdriver.go
qldbdriver/qldbdriver_test.go
qldbdriver/qldbhash.go
qldbdriver/result_test.go
qldbdriver/retry.go
qldbdriver/session.go
qldbdriver/session_management_test.go
qldbdriver/transaction_test.go

Go Driver feedback

---

qldbdriver/communicator_test.go
qldbdriver/errors.go
qldbdriver/integration_base.go
qldbdriver/qldbdriver.go
qldbdriver/qldbdriver_test.go
qldbdriver/qldbhash.go
qldbdriver/result_test.go
qldbdriver/session_management_test.go
qldbdriver/session_test.go
qldbdriver/statement_execution_test.go
qldbdriver/transaction.go
qldbdriver/transaction_test.go

Replacing panics with errors + other error handling improvements.

Improve/Expand Error handling

---

qldbdriver/qldbdriver.go
qldbdriver/result.go
qldbdriver/result_test.go
qldbdriver/statement_execution_test.go
qldbdriver/transaction.go
qldbdriver/transaction_test.go

Rework iterator pattern for result.Next()

---

qldbdriver/logger.go
qldbdriver/retry.go
qldbdriver/transaction.go

Add documentation to exported functions.

Add documentation to public functions

---

qldbdriver/qldbdriver.go
qldbdriver/qldbdriver_test.go

Remove dependency to ```vitess```

Remove sync2 dependency

---

qldbdriver/qldbdriver.go

Handling cancellation or expiry of context in driver

Handling cancellation or expiry of context in driver

---

qldbdriver/communicator.go
qldbdriver/communicator_test.go
qldbdriver/errors.go
qldbdriver/integration_base_test.go
qldbdriver/logger.go
qldbdriver/qldbdriver.go
qldbdriver/qldbdriver_test.go
qldbdriver/qldbhash.go
qldbdriver/result.go
qldbdriver/result_test.go
qldbdriver/retry.go
qldbdriver/session_management_test.go
qldbdriver/session_test.go
qldbdriver/statement_execution_test.go
qldbdriver/transaction.go
qldbdriver/transaction_test.go

Miscellaneous Improvements

---

go.mod
go.sum

-Successfully ran unit, integration, perf test

Update Ion dependencies to 1.0.1

---

go.mod
go.sum

Update Ion dependencies

---

qldbdriver/communicator.go

This is not customer impacting.
Adding userAgent to startSession request.

send user agent for startSession

---

CHANGELOG.md
qldbdriver/communicator.go

Bump version to v1.1.0 and update CHANGELOG

---

qldbdriver/communicator_test.go
qldbdriver/integration_base_test.go
qldbdriver/logger.go
qldbdriver/qldbdriver.go
qldbdriver/result.go
qldbdriver/result_test.go
qldbdriver/session_management_test.go
qldbdriver/statement_execution_test.go
qldbdriver/transaction.go
qldbdriver/transaction_test.go

Adjustments to the Result and Logger Interfaces

---

qldbdriver/integration_base_test.go
qldbdriver/logger.go
qldbdriver/qldbdriver.go
qldbdriver/result.go
qldbdriver/result_test.go
qldbdriver/session_management_test.go
qldbdriver/statement_execution_test.go
qldbdriver/transaction.go
qldbdriver/transaction_test.go

Adjustments to the logger and result interfaces.
Meant to address https://github.com/awslabs/amazon-qldb-driver-go/issues/38

Driver Interface Enhancements

---

README.md

Update readme.md with badges

---

CHANGELOG.md
README.md
go.mod

Update module to v2 for 2.0.2 release

---

CHANGELOG.md
README.md
go.mod
qldbdriver/communicator.go
qldbdriver/qldbdriver.go

Prepare for `v3.0.0` release.
#45 
* Update CHANGELOG.md
* Update driver version in user agent

Update CHANGELOG.md to v3.0

---

CHANGELOG.md
qldbdriver/communicator.go

bump repo assets for v3.0.1

---

.github/workflows/go.yml
qldbdriver/integration_base_test.go
qldbdriver/session_management_test.go
qldbdriver/statement_execution_test.go

chore: unique ledger name for parallel integration tests

---

.github/workflows/go.yml
README.md

- chore: update go versions in text matrix
- chore: disable fail-fast for Github checks
- chore: adding workflow status badges

update go versions
